### ISSUE TITLE
Geometry, FeatureService reference not found.

### ISSUE THREAD

**Issue by meghan452** [Esri/arcgis-toolkit-sl-wpf#11]
CS0234	The type or namespace name 'Geometry' does not exist in the namespace 'ESRI.ArcGIS.Client' (are you missing an assembly reference?)	ESRI.ArcGIS.Client.Toolkit.DataSources	D:\arcgis-toolkit-sl-wpf-master\src\CommonAPI\API\ESRI.ArcGIS.Client.Toolkit.DataSources\Wmts\Wmts.cs	15	Active

I downloaded arcgis-toolkit-sl-wpf-master.zip and opened solution file in Visual Studio. I got above error building api.

Can someone help me with this?

![image](https://user-images.githubusercontent.com/53577994/67321216-3f645300-f4dd-11e9-969e-6154ca938a15.png)

Screenshot attached.

Meghan Kulkarni

**Comment by mbranscomb** [comment]
ArcGIS API for Silverlight and ArcGIS Runtime SDK for WPF were retired on July 1, 2016.

We recommend you explore WPF solutions based on the ArcGIS Runtime SDK for .NET.

We recommend you explore Web solutions based on the ArcGIS API for JavaScript.

**Comment by meghan452** [comment]
I've seen that. We're working on getting out platform upgraded. However, at this moment is there any way to fix the above error? I just want to compile API and receive dll?

Thanks. 
Meghan Kulkarni

**Comment by mbranscomb** [comment]
@meghan452 

It looks like the Solution is failing to restore the NuGet package `ESRI.ArcGIS.Client'. Because this product is retired, it has been unlisted on NuGet.org, but a project/solution Restore should still be able to reach and restore the package.

Does your Visual Studio installation have a NuGet.org package source? (see https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio for more info)

**Comment by meghan452** [comment]
@mbranscomb  I appreciate prompt response. I was missing it. I got in installed. I get below error now

![image](https://user-images.githubusercontent.com/53577994/67324239-80f6fd00-f4e1-11e9-9448-bf71c8f067d5.png)

CS1061	'Editor' does not contain a definition for 'SnapDistanceSymbol' and no extension method 'SnapDistanceSymbol' accepting a first argument of type 'Editor' could be found (are you missing a using directive or an assembly reference?)	ESRI.ArcGIS.Client.Toolkit	D:\arcgis-toolkit-sl-wpf-master\src\CommonAPI\API\ESRI.ArcGIS.Client.Toolkit\Editor\EditorWidget.cs	50	Active

**Comment by meghan452** [comment]
![image](https://user-images.githubusercontent.com/53577994/67324288-98ce8100-f4e1-11e9-8471-16032560fa69.png)

**Comment by meghan452** [comment]
@mbranscomb nvm. I was missing ESRI SDK's for Silverlight. I got it resolved.

Thanks.
